// <auto-generated />
namespace WindowsFormsApplication5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delete_manymany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_manymany));
        
        string IMigrationMetadata.Id
        {
            get { return "201612071823116_delete_manymany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
